### ISSUE TITLE
Moderation

### ISSUE THREAD

**Issue by KillariDev** [DecentralisedGaming/Book#20]
I think we could also have a section about moderation. This is lesser issue in centralized platforms where we can have moderators taking care of cheaters/botters/abusers/griefers etc. But in a decentralized games these are harder to combat. 

These could be combated with some kind of sybil resistance (this could be a topic on its own too) or somekind of voting DAO.

**Comment by DecentralisedGaming** [comment]
Yeah, this is one of the pain points which I was intending to cover lightly in Chapter 4. I'd introduce the problem, but not offer solutions in that chapter necessarily. Some of that might be later.

The main folks I discuss with have two documents for pain points. One public and one private. I don't recall the link for the public one at the moment (on my other computer). There was an overlap with the points that I know you put into a document one time too.

A summary of the main pain points from the public doc can be found in the following blog though:
https://medium.com/web3foundation/blockchain-gaming-unconference-outcomes-51dfca561801

### additionally

* One point of moderation is about the chat channels, another is about advertising (if you permit that in game). One thought I had was to make chat channels opt-in. There could be an official channel which is mostly filtered for bad words (perhaps centralised). The idea is to provide something that players can use without running regulatory risks. However, players could easily add their own chat channels "to the game". Those channels would appear in-game and could be completely unfiltered, but they would be opt-in rather than being forced to see them.
* The Xaya team had similar concerns for the advertising that they offer in-game. They wondered if that aspect should be centralised. Not sure if what the current status is.
* Could there be illegal content stored on a gaming chain? How to police this.
* For botting, I know Andy from Xaya prefers PVP, but I'd prefer another method. I hope some better designed game mechanics plus verification can help here.
* Voting on a DAO is probably for the chapter on Governance: #11

**Comment by KillariDev** [comment]
If you have option for players to create their own content. You'll need to moderate that as well. You might be aware of TTP metric (Time To Penis). https://www.engadget.com/2009-03-24-overheard-gdc09-ttp-time-to-penis.html

**Comment by EdwardAThomson** [comment]
Yep, that's basically the issue for Xaya including advertising in their games.
